name: Build & Test on LE and BE

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    # ---------- Little Endian (native amd64) ----------
    - name: Install deps for native build
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ pkg-config

    - name: Build native (Little Endian)
      run: |
        cmake -B build-le -S .
        cmake --build build-le --config Release

    - name: Run native (Little Endian)
      run: ./build-le/test-exif ./test-images/1.jpg

    # ---------- Big Endian (ppc64 in Docker + QEMU) ----------
    - name: Enable QEMU for multi-arch Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build & Run inside PPC64 container (Big Endian)
      run: |
        docker run --rm --platform=linux/ppc64 \
          -v $PWD:/src -w /src \
          ubuntu:22.04 bash -c "
            apt-get update &&
            apt-get install -y cmake g++ pkg-config &&
            cmake -B build-be -S . &&
            cmake --build build-be --config Release &&
            ./build-be/test-exif ./test-images/1.jpg
          "
