name: Build & Test on LE and BE

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    # ---------- Little Endian (native amd64) ----------
    - name: Install deps for native build
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ pkg-config

    - name: Build native (Little Endian)
      run: |
        cmake -B build-le -S .
        cmake --build build-le --config Release

    - name: Run native (Little Endian)
      run: ./build-le/test-exif ./test-images/board.jpg

    # ---------- Big Endian (ppc64 cross-compile + QEMU) ----------
    - name: Install PPC64 cross-compiler & QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-powerpc64-linux-gnu qemu-user

    - name: Cross compile for PPC64 (Big Endian)
      run: |
        cmake -B build-be -S . \
          -DCMAKE_C_COMPILER=powerpc64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=powerpc64-linux-gnu-g++ \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_EXE_LINKER_FLAGS="-static"
        cmake --build build-be --config Release

    - name: Run PPC64 (Big Endian) binary under QEMU
      run: qemu-ppc64 ./build-be/test-exif ./test-images/board.jpg
