name: Build test-exif

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Run executable
      run: ./build/test-exif ./test-images/sony-alpha-6000.jpg

    - name: 20151204_224123.jpg
      run: ./build/test-exif ./test-images/20151204_224123.jpg

    - name: 20240616_100257.jpg
      run: ./build/test-exif ./test-images/20240616_100257.jpg